name = openssh
version = 8.5p1
URL = https://cloudflare.cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-$(version).tar.gz

dependencies = openssl zlib

SYSCONF ?= ../../
include $(SYSCONF)/package.mk
