name = libressl
version = 3.3.1
release = 0
URL = https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-$(version).tar.gz

configure_backend = configure_autotools

SYSCONF ?= ../../
include $(SYSCONF)/package.mk
