name = abuild
version = 3.6.0
release = 0
URL = https://dev.alpinelinux.org/archive/abuild/abuild-$(version).tar.bz2

dependencies = gnupg

MAKE_INSTALL_OPTIONS_USER = prefix=$(PREFIX)

SYSCONF ?= ../../
include $(SYSCONF)/package.mk
