name = pkg-config
version = 0.29.2
URL = http://pkgconfig.freedesktop.org/releases/pkg-config-$(version).tar.gz

CONFIGURE_OPTIONS_USER = --with-internal-glib


SYSCONF ?= ../../
include $(SYSCONF)/package.mk
