name = python
version = 3.9.2
URL = https://www.python.org/ftp/python/$(version)/Python-$(version).tar.xz

pkg_build_dir = $(pkg_build_par_dir)/Python-$(version)

build-dependencies = libffi libffi-dev python-dev

SYSCONF ?= ../../
include $(SYSCONF)/package.mk
