name = libassuan
version = 2.5.5
URL = https://gnupg.org/ftp/gcrypt/libassuan/libassuan-$(version).tar.bz2

build-dependencies = libgpg-error libgpg-error-dev

SYSCONF ?= ../../
include $(SYSCONF)/package.mk
