name = libnpth
version = 1.6
release = 0
URL = https://gnupg.org/ftp/gcrypt/npth/npth-$(version).tar.bz2

pkg_build_dir = $(pkg_build_par_dir)/npth-$(version)

SYSCONF ?= ../../
include $(SYSCONF)/package.mk
