name = autoconf
version = 2.71
release = 0
URL = https://ftp.gnu.org/gnu/autoconf/autoconf-$(version).tar.gz

dependencies = m4 perl

# TODO: ln $(which m4) /usr/bin/m4

SYSCONF ?= ../../
include $(SYSCONF)/package.mk
