name = libtermkey
version = 0.22
URL = http://www.leonerd.org.uk/code/libtermkey/libtermkey-$(version).tar.gz

build-dependencies = pkgconf ncurses-dev libtool

SYSCONF ?= ../../
include $(SYSCONF)/package.mk
