name = gc
version = 8.0.4
release = 0
URL = https://github.com/ivmai/bdwgc/releases/download/v$(version)/gc-$(version).tar.gz

CONFIGURE_OPTIONS_USER = --enable-static

SYSCONF ?= ../../
include $(SYSCONF)/package.mk

configure_cmake:
	@true
