name = rsync
version = 3.2.3
URL = https://download.samba.org/pub/rsync/src/rsync-$(version).tar.gz

CONFIGURE_OPTIONS_USER = --disable-xxhash --disable-lz4

SYSCONF ?= ../../
include $(SYSCONF)/package.mk
