name = alsa-lib
version = 1.2.3
URL = ftp://ftp.alsa-project.org/pub/lib/alsa-lib-$(version).tar.bz2

description = "alsa-lib contains the user space library that developers compile ALSA applications against."

SYSCONF ?= ../../
include $(SYSCONF)/package.mk
