name = libtorrent
version = 0.13.8
# WARNING: this should be updated at each new rtorrent release
URL = https://github.com/rakshasa/rtorrent/releases/download/v0.9.8/$(name)-$(version).tar.gz

SYSCONF ?= ../../
include $(SYSCONF)/package.mk
