name = zsh
version = 5.7.1
URL = https://downloads.sourceforge.net/project/zsh/zsh/$(version)/zsh-$(version).tar.xz

CONFIGURE_OPTIONS_USER = --with-tcsetpgrp
dependencies = ncurses

SYSCONF ?= ../../
include $(SYSCONF)/package.mk
