name = libevent
version = 2.1.12
URL = https://github.com/libevent/libevent/releases/download/release-$(version)-stable/libevent-$(version)-stable.tar.gz

pkg_build_dir = $(pkg_build_par_dir)/libevent-$(version)-stable

SYSCONF ?= ../../
include $(SYSCONF)/package.mk
