name = rtorrent
version = 0.9.8
URL = https://github.com/rakshasa/rtorrent/releases/download/v$(version)/rtorrent-$(version).tar.gz

build-dependencies = curl-dev libtorrent libtorrent-dev

SYSCONF ?= ../../
include $(SYSCONF)/package.mk
