name = libnl
version = 3.5.0
pversion = 3_5_0
URL = https://github.com/thom311/libnl/releases/download/libnl$(pversion)/libnl-$(version).tar.gz

CONFIGURE_OPTIONS_USER = --disable-debug

SYSCONF ?= ../../
include $(SYSCONF)/package.mk
