name = util-linux
version = 2.36
URL = https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v$(version)/util-linux-$(version).tar.xz

build-dependencies = zlib-dev musl-dev linux-dev rc

SYSCONF ?= ../../
include $(SYSCONF)/package.mk
