name = linux-firmware
version = 20210315
URL = https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/snapshot/linux-firmware-$(version).tar.gz

description = "linux-firmware contains binary drivers for various third-party products."

SYSCONF ?= ../../
include $(SYSCONF)/package.mk

configure_autotools:
	@true
